# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe2888b1838be9e1391635cd2fe2ee429ee0f2fa9a5f7a9aef35775b84c444e739bf5caa359726ff3648b306ad19da05d5e4f8958f75b73c55c3e4abbba3918f

test:
  secret_key_base: 151810b8c5b5c874731fd7b7210812ac9dcc228f554392e08220980ac6e3e36bbda1cbc5de4ae273c8cb7189d72b1f3c8320b74b62b6e7e4be0c26a306fd8441

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
